<?php 
$publicToken = $this->getPublicTokeniFrame();
$language = $this->getLanguage();
$dataVariant = $this->getVarient();
if (Mage::getSingleton('checkout/session')->getQuote()->getGrandTotal() < floatval(Mage::getStoreConfig('sales/minimum_order/amount'))) { ?>
	<div class="checkout-iframe" id="collectoriframe">
		<?php echo $this->__("Minimum Order amount is: %s", Mage::getStoreConfig('sales/minimum_order/amount'));?>
	</div>
<?php } else if($publicToken['error'] == 0){ ?>
	<div class='checkout-iframe' id="collectoriframe">
		<script type='text/javascript'>
			var publicToken = '<?php echo $publicToken;?>';
		</script>
		<script id='fixme' data-lang='<?php echo $language;?>' data-token='<?php echo $publicToken['message'];?>' src='<?php echo $this->getIframeSrc();?>' <?php echo $dataVariant;?>></script>
	</div>
<?php } 

	else { ?>
	<div class="checkout-iframe" id="collectoriframe">

		<?php
        if (isset($publicToken['message'])){
            if (isset($publicToken['message']['errors'])){
                if (isset($publicToken['message']['errors'][0])){
                    if (isset($publicToken['message']['errors'][0]['message'])){
                        echo $this->__($publicToken['message']['errors'][0]['message']);
                    }
                }
            }
            else {
                echo $publicToken['message'];
            }
        }

		ob_start();
		var_dump($publicToken);
		Mage::log('Public token is missing, message: ' . ob_get_clean(), null,'cartiframe.log');?>
	</div>
<?php }   ?>