
<?php
$session = Mage::getSingleton('checkout/session');
$publicToken = $session->getSuccessPublicToken();
$language = $session->getLanguage();
$dataVariant = $session->getDataVariant();
$src = $session->getSrc();
$this->unsSession();
?>
<div class='checkout-iframe'>
	<script type='text/javascript'>
		var publicToken = '<?php echo $publicToken; ?>';
	</script>
	<script id='fixme' data-lang='<?php echo $language;?>' data-token='<?php echo $publicToken;?>' src='<?php echo $src;?>' <?php echo $dataVariant;?>></script>		
</div>
<?php
$session->setData('business_public_token', null);
$session->setData('success_public_token', null);
$session->setData('business_private_id', null);
$session->setData('business_hashstr', null);
$session->setData('public_token', null);
$session->setData('success_public_token', null);
$session->setData('private_id', null);
$session->setData('hashstr', null);
?>