
<?php /*<form id="discount-coupon-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">*/?>
<form id="discount-coupon-form" action="<?php echo $this->getFormActionUrl() ?>" method="post">
    <div class="discount">
        <?php /*<h2><?php echo $this->__('Discount Codes') ?></h2>*/?>
        <div class="discount-form">
             <?php /*<label for="coupon_code"><?php echo $this->__('Discount Codes') ?></label>*/?>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
			<input type="hidden" name="return_url" id="return_url" value="<?php echo Mage::getBaseUrl() . 'collectorcheckout' ?>"/>
            <div class="field-wrapper">
                <input class="input-text" placeholder="<?php echo $this->__('Voucher')?>" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
                <?php if(strlen($this->getCouponCode())){ ?>
                <div class="button-wrapper cancelactive">
                <?php } else { ?>
                <div class="button-wrapper">
                <?php } ?>
                    <button type="button" title="<?php echo $this->__('Apply') ?>" class="button2 apply" onclick="discountCoupon('<?php echo $this->getFormActionUrl() ?>', 0)" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    <?php if(strlen($this->getCouponCode())): ?>
                        <button type="button" title="<?php $this->__('Cancel') ?>" class="button2 cancel-coupon" onclick="discountCoupon('<?php echo $this->getFormActionUrl() ?>', 1)" value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span>
                        </button>
                    <?php endif;?>
                </div>
            </div>
        
        </div>
    </div>
</form>

<?php if(Mage::getStoreConfig('ecomatic_collectorbank/general/show_newsletter')):?>
	<form id="cart_subscription" action="" method="post">
		<div class="discount-newsletter">
			<input type="hidden" name="is_news_subscription" id="subscription" value="0" />

			<?php /*<label><input type="checkbox" name="is_subscribed"/><?php echo $this->__('Yes, I want to subscribe to newsletters');?></label>*/?>

			<input type="checkbox" id="c1" name="cc"/>
			<label for="c1"><span></span><?php echo $this->__('Yes, I want to subscribe to newsletters');?></label>

		</div>
	</form>
<?php endif;?>

